### ISSUE TITLE
Centre frequency is reported incorrectly on older files

### ISSUE THREAD

**Issue by sjperkins** [ska-sa/katdal#108]
katdal version is `0.9.dev569+master.1a0f71c`

For the below observation, the Centre Frequency is reported as .428Ghz. The channels then get shifted accordingly and we end up with a band of 0.0 - .856 Ghz.

```
K = katdal.open('/var/kat/archive2/data/MeerKATAR1/telescope_products/2017/09/14/1505426738.h5')
>>> K
<katdal.H5DataV3 '/var/kat/archive2/data/MeerKATAR1/telescope_products/2017/09/14/1505426738.h5' shape (1846, 32768, 544) at 0x7fb0a769ee50>
>>> print K
===============================================================================
Name: /var/kat/archive2/data/MeerKATAR1/telescope_products/2017/09/14/1505426738.h5 (version 3.0)
===============================================================================
Observer: Tom  Experiment ID: 20170914-0179
Description: 'MKAIV-608 Imaging observation PHOENIX_DEEP'
Observed from 2017-09-14 22:05:38.379 UTC to 2017-09-15 02:11:40.134 UTC
Dump rate / period: 0.12505 Hz / 7.997 s
Subarrays: 1
  ID  Antennas                            Inputs  Corrprods
   0  m000,m002,m005,m017,m020,m021,m034,m041,m042,m043,m048,m049,m050,m054,m055,m056  32      544
Spectral Windows: 1
  ID Band Product  CentreFreq(MHz)  Bandwidth(MHz)  Channels  ChannelWidth(kHz)
   0 L    c856M32k    428.000         856.000          32768        26.123
-------------------------------------------------------------------------------
Data selected according to the following criteria:
  subarray=0
  ants=['m054', 'm055', 'm056', 'm043', 'm042', 'm041', 'm002', 'm000', 'm005', 'm017', 'm021', 'm020', 'm034', 'm049', 'm050', 'm048']
  spw=0
-------------------------------------------------------------------------------
```

This value seems to be obtained from  `center_freq` attribute on `TelescopeModel.cbf`:

```
>>> K.file['TelescopeModel']['cbf'].attrs['center_freq']
428000000.0
>>> K.file['TelescopeState'].attrs['sdp_l0_center_freq']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/kat/ve/local/lib/python2.7/site-packages/h5py/_hl/attrs.py", line 60, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 77, in h5py.h5a.open
KeyError: "Can't open attribute (can't locate attribute in name index)"
```

**Comment by sjperkins** [comment]
This may have been caused by https://github.com/ska-sa/katdal/pull/105
