### ISSUE TITLE
missing source.timestamps in 1535789408_sdp_l0.full.rdb

### ISSUE THREAD

**Issue by SpheMakh** [ska-sa/katdal#184]
I'm getting this error when converting this data set into an MS using mvftoms.py. 

```
  File "/usr/local/bin/mvftoms.py", line 777, in <module>
    main()
  File "/usr/local/bin/mvftoms.py", line 254, in main
    dataset = katdal.open(open_args, ref_ant=options.ref_ant)
  File "/usr/local/lib/python2.7/dist-packages/katdal/__init__.py", line 336, in open
    ref_ant, time_offset, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/katdal/visdatav4.py", line 112, in __init__
    num_dumps = len(source.timestamps)
TypeError: object of type 'NoneType' has no len()
```

**Comment by ludwigschwardt** [comment]
I can't reproduce this with the latest katdal master. The following succeeds on imgr-com-4:

```
 f = katdal.open('1535789408_sdp_l0.full.rdb')
```

I'd still like to know what fixes this since @vasaantk had this problem too.

**Comment by SpheMakh** [comment]
I switched to master and that problem went away. But now I'm getting different errors:

1. The DaskLazyIndexer 

```
scan   1 (   3 samples) loaded. Target: 'J124906-1941'. Writing to disk...
Traceback (most recent call last):
  File "/usr/local/bin/mvftoms.py", line 791, in <module>
    main()
  File "/usr/local/bin/mvftoms.py", line 541, in main
    scan_vis_data, scan_weight_data, scan_flag_data)
  File "/usr/local/bin/mvftoms.py", line 72, in load
    da.store([dataset.vis._dask_getitem(indices),
AttributeError: 'DaskLazyIndexer' object has no attribute 'dask_getitem'
Traceback (most recent call last):
  File "/code/run.py", line 32, in <module>
    utils.xrun(cab["binary"], args+files )
  File "/utils/utils/__init__.py", line 74, in xrun
    raise SystemError('%s: returns errr code %d'%(command, process.returncode))
SystemError: mvftoms.py: returns errr code 1
```

I fixed by changing `dask_getitem` to `__getitem__` in lines 72-74 of mvftoms.py

2.  All sources must be dask objects

```
scan   1 (   3 samples) loaded. Target: 'J124906-1941'. Writing to disk...
Traceback (most recent call last):
  File "/usr/local/bin/mvftoms.py", line 791, in <module>
    main()
  File "/usr/local/bin/mvftoms.py", line 541, in main
    scan_vis_data, scan_weight_data, scan_flag_data)
  File "/usr/local/bin/mvftoms.py", line 75, in load
    [vis, weights, flags], lock=False)
  File "/usr/local/lib/python2.7/dist-packages/dask/array/core.py", line 943, in store
    raise ValueError("All sources must be dask array objects")
ValueError: All sources must be dask array objects
Traceback (most recent call last):
  File "/code/run.py", line 32, in <module>
    utils.xrun(cab["binary"], args+files )
  File "/utils/utils/__init__.py", line 74, in xrun
    raise SystemError('%s: returns errr code %d'%(command, process.returncode))
SystemError: mvftoms.py: returns errr code 1
```

:sos:

**Comment by bmerry** [comment]
@SpheMakh see if #185 fixes this for you.

**Comment by SpheMakh** [comment]
That did it. Thanks @bmerry
