### ISSUE TITLE
mvftoms.py crashing on 'chunk_name not found'

### ISSUE THREAD

**Issue by ifornax** [ska-sa/katdal#193]
Hi 

I have been running the mvftoms.py on the recent 1K dataset 1539238540_sdp_l0.full.rdb  on chpc-com4 

Please find the error message I am getting:

```
nadeem@imgr-com-4:/data/nadeem/MeerKAT/1K_Mode$ mvftoms.py -m --caltables 1539238540_sdp_l0.full.rdb 
/home/nadeem/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using 'pyrap' casacore binding to produce MS
Traceback (most recent call last):
  File "/home/nadeem/.local/bin/mvftoms.py", line 787, in <module>
    main()
  File "/home/nadeem/.local/bin/mvftoms.py", line 245, in main
    dataset = katdal.open(open_args, ref_ant=options.ref_ant)
  File "/home/nadeem/.local/lib/python2.7/site-packages/katdal/__init__.py", line 335, in open
    dataset = VisibilityDataV4(open_data_source(f, **kwargs),
  File "/home/nadeem/.local/lib/python2.7/site-packages/katdal/datasources.py", line 395, in open_data_source
    return TelstateDataSource.from_url(url, **kwargs)
  File "/home/nadeem/.local/lib/python2.7/site-packages/katdal/datasources.py", line 388, in from_url
    chunk_store = _infer_chunk_store(url_parts, telstate, **kwargs)
  File "/home/nadeem/.local/lib/python2.7/site-packages/katdal/datasources.py", line 292, in _infer_chunk_store
    data_path = os.path.join(store_path, telstate['chunk_name'])
  File "/home/nadeem/.local/lib/python2.7/site-packages/katsdptelstate/telescope_state.py", line 223, in __getitem__
    return self._get(key)
  File "/home/nadeem/.local/lib/python2.7/site-packages/katsdptelstate/telescope_state.py", line 500, in _get
    raise KeyError('{} not found'.format(key))
KeyError: 'chunk_name not found'
```

**Comment by ludwigschwardt** [comment]
You need the master branch to open the latest files... I'll need a new release soon!

**Comment by ludwigschwardt** [comment]
Try the latest release (0.11) and let me know if it solves your problem.

**Comment by ludwigschwardt** [comment]
Looks good! The cal solution tables are still a work in progress anyway, so I would not worry too much.
