### ISSUE TITLE
casacore missing as a dependency

### ISSUE THREAD

**Issue by Mulan-94** [ska-sa/katdal#371]
Hi there,

Trying to run `mvftoms --help` and I get:
```
Traceback (most recent call last):
  File "/home/v_envs/katdal/bin/mvftoms.py", line 39, in <module>
    from katdal import averager, ms_async, ms_extra
  File "/home/v_envs/katdal/lib/python3.8/site-packages/katdal/ms_async.py", line 36, in <module>
    from . import ms_extra
  File "/home/v_envs/katdal/lib/python3.8/site-packages/katdal/ms_extra.py", line 27, in <module>
    import casacore
ModuleNotFoundError: No module named 'casacore'

```
installing `python-casacore` seems to help. Perhaps it's a missing required dependency?

Tested on: `python 3.8`

**Comment by ludwigschwardt** [comment]
Indeed, as @bennahugo said: `pip install katdal[ms]`.

The `s3` option still exists but does nothing. It is safe to leave that out.
